package me.bs.java.usermanagement.backend.mapper;

import java.util.List;
import java.util.Map;
import me.bs.java.usermanagement.backend.model.Person;
import me.bs.java.usermanagement.backend.model.PersonCriteria.Criteria;
import me.bs.java.usermanagement.backend.model.PersonCriteria.Criterion;
import me.bs.java.usermanagement.backend.model.PersonCriteria;
import org.apache.ibatis.jdbc.SQL;

public class PersonSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String countByExample(PersonCriteria example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("PERSON");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String deleteByExample(PersonCriteria example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("PERSON");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String insertSelective(Person record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("PERSON");
		if (record.getProxy() != null) {
			sql.VALUES("PROXY", "#{proxy,jdbcType=VARCHAR}");
		}
		if (record.getTitle() != null) {
			sql.VALUES("TITLE", "#{title,jdbcType=VARCHAR}");
		}
		if (record.getFirstName() != null) {
			sql.VALUES("FIRST_NAME", "#{firstName,jdbcType=VARCHAR}");
		}
		if (record.getLastName() != null) {
			sql.VALUES("LAST_NAME", "#{lastName,jdbcType=VARCHAR}");
		}
		if (record.getFullName() != null) {
			sql.VALUES("FULL_NAME", "#{fullName,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			sql.VALUES("EMAIL", "#{email,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String selectByExample(PersonCriteria example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("ID");
		} else {
			sql.SELECT("ID");
		}
		sql.SELECT("PROXY");
		sql.SELECT("TITLE");
		sql.SELECT("FIRST_NAME");
		sql.SELECT("LAST_NAME");
		sql.SELECT("FULL_NAME");
		sql.SELECT("EMAIL");
		sql.FROM("PERSON");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		Person record = (Person) parameter.get("record");
		PersonCriteria example = (PersonCriteria) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("PERSON");
		if (record.getId() != null) {
			sql.SET("ID = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getProxy() != null) {
			sql.SET("PROXY = #{record.proxy,jdbcType=VARCHAR}");
		}
		if (record.getTitle() != null) {
			sql.SET("TITLE = #{record.title,jdbcType=VARCHAR}");
		}
		if (record.getFirstName() != null) {
			sql.SET("FIRST_NAME = #{record.firstName,jdbcType=VARCHAR}");
		}
		if (record.getLastName() != null) {
			sql.SET("LAST_NAME = #{record.lastName,jdbcType=VARCHAR}");
		}
		if (record.getFullName() != null) {
			sql.SET("FULL_NAME = #{record.fullName,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			sql.SET("EMAIL = #{record.email,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("PERSON");
		sql.SET("ID = #{record.id,jdbcType=BIGINT}");
		sql.SET("PROXY = #{record.proxy,jdbcType=VARCHAR}");
		sql.SET("TITLE = #{record.title,jdbcType=VARCHAR}");
		sql.SET("FIRST_NAME = #{record.firstName,jdbcType=VARCHAR}");
		sql.SET("LAST_NAME = #{record.lastName,jdbcType=VARCHAR}");
		sql.SET("FULL_NAME = #{record.fullName,jdbcType=VARCHAR}");
		sql.SET("EMAIL = #{record.email,jdbcType=VARCHAR}");
		PersonCriteria example = (PersonCriteria) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String updateByPrimaryKeySelective(Person record) {
		SQL sql = new SQL();
		sql.UPDATE("PERSON");
		if (record.getProxy() != null) {
			sql.SET("PROXY = #{proxy,jdbcType=VARCHAR}");
		}
		if (record.getTitle() != null) {
			sql.SET("TITLE = #{title,jdbcType=VARCHAR}");
		}
		if (record.getFirstName() != null) {
			sql.SET("FIRST_NAME = #{firstName,jdbcType=VARCHAR}");
		}
		if (record.getLastName() != null) {
			sql.SET("LAST_NAME = #{lastName,jdbcType=VARCHAR}");
		}
		if (record.getFullName() != null) {
			sql.SET("FULL_NAME = #{fullName,jdbcType=VARCHAR}");
		}
		if (record.getEmail() != null) {
			sql.SET("EMAIL = #{email,jdbcType=VARCHAR}");
		}
		sql.WHERE("ID = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected void applyWhere(SQL sql, PersonCriteria example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}