package me.bs.java.usermanagement.backend.mapper;

import java.util.List;
import me.bs.java.usermanagement.backend.model.Person;
import me.bs.java.usermanagement.backend.model.PersonCriteria;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface PersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@SelectProvider(type = PersonSqlProvider.class, method = "countByExample")
	long countByExample(PersonCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@DeleteProvider(type = PersonSqlProvider.class, method = "deleteByExample")
	int deleteByExample(PersonCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Delete({ "delete from PERSON", "where ID = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Insert({ "insert into PERSON (PROXY, TITLE, ", "FIRST_NAME, LAST_NAME, ", "FULL_NAME, EMAIL)",
			"values (#{proxy,jdbcType=VARCHAR}, #{title,jdbcType=VARCHAR}, ",
			"#{firstName,jdbcType=VARCHAR}, #{lastName,jdbcType=VARCHAR}, ",
			"#{fullName,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR})" })
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@InsertProvider(type = PersonSqlProvider.class, method = "insertSelective")
	@SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@SelectProvider(type = PersonSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "PROXY", property = "proxy", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TITLE", property = "title", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FIRST_NAME", property = "firstName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "LAST_NAME", property = "lastName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FULL_NAME", property = "fullName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR) })
	List<Person> selectByExampleWithRowbounds(PersonCriteria example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@SelectProvider(type = PersonSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "PROXY", property = "proxy", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TITLE", property = "title", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FIRST_NAME", property = "firstName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "LAST_NAME", property = "lastName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FULL_NAME", property = "fullName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR) })
	List<Person> selectByExample(PersonCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Select({ "select", "ID, PROXY, TITLE, FIRST_NAME, LAST_NAME, FULL_NAME, EMAIL", "from PERSON",
			"where ID = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "ID", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "PROXY", property = "proxy", jdbcType = JdbcType.VARCHAR),
			@Result(column = "TITLE", property = "title", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FIRST_NAME", property = "firstName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "LAST_NAME", property = "lastName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "FULL_NAME", property = "fullName", jdbcType = JdbcType.VARCHAR),
			@Result(column = "EMAIL", property = "email", jdbcType = JdbcType.VARCHAR) })
	Person selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@UpdateProvider(type = PersonSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@UpdateProvider(type = PersonSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") Person record, @Param("example") PersonCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@UpdateProvider(type = PersonSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Update({ "update PERSON", "set PROXY = #{proxy,jdbcType=VARCHAR},", "TITLE = #{title,jdbcType=VARCHAR},",
			"FIRST_NAME = #{firstName,jdbcType=VARCHAR},", "LAST_NAME = #{lastName,jdbcType=VARCHAR},",
			"FULL_NAME = #{fullName,jdbcType=VARCHAR},", "EMAIL = #{email,jdbcType=VARCHAR}",
			"where ID = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(Person record);
}