
insert into PERSON (ID, PROXY, FIRST_NAME, LAST_NAME, FULL_NAME, TITLE, EMAIL) 
values(10001,'10001', 'MICHAEL','FOX','MICHAEL FOX','Mr.','MICHAEL.FOX.ABC.COM' );

insert into PERSON (ID, PROXY, FIRST_NAME, LAST_NAME, FULL_NAME, TITLE, EMAIL) 
values(10002,'10002', 'JAMES','FOX','JAMES FOX','Mr.','JAMES.FOX.ABC.COM' );

