
/* 
create schema mydb;
*/
/*
drop table PERSON;
drop table PHONE;
drop table ADDRESS;
*/
create table PERSON
(
   ID BIGINT  AUTO_INCREMENT,
   PROXY varchar(255) ,
   TITLE varchar(10) ,
   FIRST_NAME varchar(200) ,
   LAST_NAME varchar(200) ,
   FULL_NAME varchar(600) ,
   EMAIL varchar(200) ,
   primary key(ID)
);

CREATE TABLE PHONE 
(
	ID BIGINT  AUTO_INCREMENT,
	NUMBER VARCHAR(255),
	IS_PRIMARY VARCHAR(255), 
	PROXY VARCHAR(255), 
	PHONE_TYPE VARCHAR(10), 
	PERSON_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)
) ;

CREATE TABLE ADDRESS 
(
	ID BIGINT  AUTO_INCREMENT,
	PROXY VARCHAR(255),
	IS_PRIMARY VARCHAR(255), 
	ADDRESS_TYPE VARCHAR(255),
	LINE1 VARCHAR(255), 
	LINE2 VARCHAR(255), 
	LINE3 VARCHAR(255), 
	LINE4 VARCHAR(255), 
	LINE5 VARCHAR(255), 
	CITY VARCHAR(255), 
	STATE VARCHAR(255), 
	ZIP VARCHAR(255), 
	COUNTRY VARCHAR(255), 
	PERSON_ID BIGINT,
	PRIMARY KEY (ID),
	FOREIGN KEY (PERSON_ID) REFERENCES PERSON(ID)

) ;

