package me.bs.java.usermanagement.backend.model;

import java.util.ArrayList;
import java.util.List;

public class AddressCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public AddressCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProxyIsNull() {
			addCriterion("PROXY is null");
			return (Criteria) this;
		}

		public Criteria andProxyIsNotNull() {
			addCriterion("PROXY is not null");
			return (Criteria) this;
		}

		public Criteria andProxyEqualTo(String value) {
			addCriterion("PROXY =", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotEqualTo(String value) {
			addCriterion("PROXY <>", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyGreaterThan(String value) {
			addCriterion("PROXY >", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyGreaterThanOrEqualTo(String value) {
			addCriterion("PROXY >=", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLessThan(String value) {
			addCriterion("PROXY <", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLessThanOrEqualTo(String value) {
			addCriterion("PROXY <=", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLike(String value) {
			addCriterion("PROXY like", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotLike(String value) {
			addCriterion("PROXY not like", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyIn(List<String> values) {
			addCriterion("PROXY in", values, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotIn(List<String> values) {
			addCriterion("PROXY not in", values, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyBetween(String value1, String value2) {
			addCriterion("PROXY between", value1, value2, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotBetween(String value1, String value2) {
			addCriterion("PROXY not between", value1, value2, "proxy");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryIsNull() {
			addCriterion("IS_PRIMARY is null");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryIsNotNull() {
			addCriterion("IS_PRIMARY is not null");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryEqualTo(String value) {
			addCriterion("IS_PRIMARY =", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryNotEqualTo(String value) {
			addCriterion("IS_PRIMARY <>", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryGreaterThan(String value) {
			addCriterion("IS_PRIMARY >", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryGreaterThanOrEqualTo(String value) {
			addCriterion("IS_PRIMARY >=", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryLessThan(String value) {
			addCriterion("IS_PRIMARY <", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryLessThanOrEqualTo(String value) {
			addCriterion("IS_PRIMARY <=", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryLike(String value) {
			addCriterion("IS_PRIMARY like", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryNotLike(String value) {
			addCriterion("IS_PRIMARY not like", value, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryIn(List<String> values) {
			addCriterion("IS_PRIMARY in", values, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryNotIn(List<String> values) {
			addCriterion("IS_PRIMARY not in", values, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryBetween(String value1, String value2) {
			addCriterion("IS_PRIMARY between", value1, value2, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryNotBetween(String value1, String value2) {
			addCriterion("IS_PRIMARY not between", value1, value2, "isPrimary");
			return (Criteria) this;
		}

		public Criteria andAddressTypeIsNull() {
			addCriterion("ADDRESS_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAddressTypeIsNotNull() {
			addCriterion("ADDRESS_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAddressTypeEqualTo(String value) {
			addCriterion("ADDRESS_TYPE =", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeNotEqualTo(String value) {
			addCriterion("ADDRESS_TYPE <>", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeGreaterThan(String value) {
			addCriterion("ADDRESS_TYPE >", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS_TYPE >=", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeLessThan(String value) {
			addCriterion("ADDRESS_TYPE <", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS_TYPE <=", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeLike(String value) {
			addCriterion("ADDRESS_TYPE like", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeNotLike(String value) {
			addCriterion("ADDRESS_TYPE not like", value, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeIn(List<String> values) {
			addCriterion("ADDRESS_TYPE in", values, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeNotIn(List<String> values) {
			addCriterion("ADDRESS_TYPE not in", values, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeBetween(String value1, String value2) {
			addCriterion("ADDRESS_TYPE between", value1, value2, "addressType");
			return (Criteria) this;
		}

		public Criteria andAddressTypeNotBetween(String value1, String value2) {
			addCriterion("ADDRESS_TYPE not between", value1, value2, "addressType");
			return (Criteria) this;
		}

		public Criteria andLine1IsNull() {
			addCriterion("LINE1 is null");
			return (Criteria) this;
		}

		public Criteria andLine1IsNotNull() {
			addCriterion("LINE1 is not null");
			return (Criteria) this;
		}

		public Criteria andLine1EqualTo(String value) {
			addCriterion("LINE1 =", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1NotEqualTo(String value) {
			addCriterion("LINE1 <>", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1GreaterThan(String value) {
			addCriterion("LINE1 >", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1GreaterThanOrEqualTo(String value) {
			addCriterion("LINE1 >=", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1LessThan(String value) {
			addCriterion("LINE1 <", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1LessThanOrEqualTo(String value) {
			addCriterion("LINE1 <=", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1Like(String value) {
			addCriterion("LINE1 like", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1NotLike(String value) {
			addCriterion("LINE1 not like", value, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1In(List<String> values) {
			addCriterion("LINE1 in", values, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1NotIn(List<String> values) {
			addCriterion("LINE1 not in", values, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1Between(String value1, String value2) {
			addCriterion("LINE1 between", value1, value2, "line1");
			return (Criteria) this;
		}

		public Criteria andLine1NotBetween(String value1, String value2) {
			addCriterion("LINE1 not between", value1, value2, "line1");
			return (Criteria) this;
		}

		public Criteria andLine2IsNull() {
			addCriterion("LINE2 is null");
			return (Criteria) this;
		}

		public Criteria andLine2IsNotNull() {
			addCriterion("LINE2 is not null");
			return (Criteria) this;
		}

		public Criteria andLine2EqualTo(String value) {
			addCriterion("LINE2 =", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2NotEqualTo(String value) {
			addCriterion("LINE2 <>", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2GreaterThan(String value) {
			addCriterion("LINE2 >", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2GreaterThanOrEqualTo(String value) {
			addCriterion("LINE2 >=", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2LessThan(String value) {
			addCriterion("LINE2 <", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2LessThanOrEqualTo(String value) {
			addCriterion("LINE2 <=", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2Like(String value) {
			addCriterion("LINE2 like", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2NotLike(String value) {
			addCriterion("LINE2 not like", value, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2In(List<String> values) {
			addCriterion("LINE2 in", values, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2NotIn(List<String> values) {
			addCriterion("LINE2 not in", values, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2Between(String value1, String value2) {
			addCriterion("LINE2 between", value1, value2, "line2");
			return (Criteria) this;
		}

		public Criteria andLine2NotBetween(String value1, String value2) {
			addCriterion("LINE2 not between", value1, value2, "line2");
			return (Criteria) this;
		}

		public Criteria andLine3IsNull() {
			addCriterion("LINE3 is null");
			return (Criteria) this;
		}

		public Criteria andLine3IsNotNull() {
			addCriterion("LINE3 is not null");
			return (Criteria) this;
		}

		public Criteria andLine3EqualTo(String value) {
			addCriterion("LINE3 =", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3NotEqualTo(String value) {
			addCriterion("LINE3 <>", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3GreaterThan(String value) {
			addCriterion("LINE3 >", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3GreaterThanOrEqualTo(String value) {
			addCriterion("LINE3 >=", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3LessThan(String value) {
			addCriterion("LINE3 <", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3LessThanOrEqualTo(String value) {
			addCriterion("LINE3 <=", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3Like(String value) {
			addCriterion("LINE3 like", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3NotLike(String value) {
			addCriterion("LINE3 not like", value, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3In(List<String> values) {
			addCriterion("LINE3 in", values, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3NotIn(List<String> values) {
			addCriterion("LINE3 not in", values, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3Between(String value1, String value2) {
			addCriterion("LINE3 between", value1, value2, "line3");
			return (Criteria) this;
		}

		public Criteria andLine3NotBetween(String value1, String value2) {
			addCriterion("LINE3 not between", value1, value2, "line3");
			return (Criteria) this;
		}

		public Criteria andLine4IsNull() {
			addCriterion("LINE4 is null");
			return (Criteria) this;
		}

		public Criteria andLine4IsNotNull() {
			addCriterion("LINE4 is not null");
			return (Criteria) this;
		}

		public Criteria andLine4EqualTo(String value) {
			addCriterion("LINE4 =", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4NotEqualTo(String value) {
			addCriterion("LINE4 <>", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4GreaterThan(String value) {
			addCriterion("LINE4 >", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4GreaterThanOrEqualTo(String value) {
			addCriterion("LINE4 >=", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4LessThan(String value) {
			addCriterion("LINE4 <", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4LessThanOrEqualTo(String value) {
			addCriterion("LINE4 <=", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4Like(String value) {
			addCriterion("LINE4 like", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4NotLike(String value) {
			addCriterion("LINE4 not like", value, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4In(List<String> values) {
			addCriterion("LINE4 in", values, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4NotIn(List<String> values) {
			addCriterion("LINE4 not in", values, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4Between(String value1, String value2) {
			addCriterion("LINE4 between", value1, value2, "line4");
			return (Criteria) this;
		}

		public Criteria andLine4NotBetween(String value1, String value2) {
			addCriterion("LINE4 not between", value1, value2, "line4");
			return (Criteria) this;
		}

		public Criteria andLine5IsNull() {
			addCriterion("LINE5 is null");
			return (Criteria) this;
		}

		public Criteria andLine5IsNotNull() {
			addCriterion("LINE5 is not null");
			return (Criteria) this;
		}

		public Criteria andLine5EqualTo(String value) {
			addCriterion("LINE5 =", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5NotEqualTo(String value) {
			addCriterion("LINE5 <>", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5GreaterThan(String value) {
			addCriterion("LINE5 >", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5GreaterThanOrEqualTo(String value) {
			addCriterion("LINE5 >=", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5LessThan(String value) {
			addCriterion("LINE5 <", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5LessThanOrEqualTo(String value) {
			addCriterion("LINE5 <=", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5Like(String value) {
			addCriterion("LINE5 like", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5NotLike(String value) {
			addCriterion("LINE5 not like", value, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5In(List<String> values) {
			addCriterion("LINE5 in", values, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5NotIn(List<String> values) {
			addCriterion("LINE5 not in", values, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5Between(String value1, String value2) {
			addCriterion("LINE5 between", value1, value2, "line5");
			return (Criteria) this;
		}

		public Criteria andLine5NotBetween(String value1, String value2) {
			addCriterion("LINE5 not between", value1, value2, "line5");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("CITY is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("CITY is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("CITY =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("CITY <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("CITY >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("CITY >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("CITY <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("CITY <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("CITY like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("CITY not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("CITY in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("CITY not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("CITY between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("CITY not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(String value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(String value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(String value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(String value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(String value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(String value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLike(String value) {
			addCriterion("STATE like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotLike(String value) {
			addCriterion("STATE not like", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<String> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<String> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(String value1, String value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(String value1, String value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andZipIsNull() {
			addCriterion("ZIP is null");
			return (Criteria) this;
		}

		public Criteria andZipIsNotNull() {
			addCriterion("ZIP is not null");
			return (Criteria) this;
		}

		public Criteria andZipEqualTo(String value) {
			addCriterion("ZIP =", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipNotEqualTo(String value) {
			addCriterion("ZIP <>", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipGreaterThan(String value) {
			addCriterion("ZIP >", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipGreaterThanOrEqualTo(String value) {
			addCriterion("ZIP >=", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipLessThan(String value) {
			addCriterion("ZIP <", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipLessThanOrEqualTo(String value) {
			addCriterion("ZIP <=", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipLike(String value) {
			addCriterion("ZIP like", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipNotLike(String value) {
			addCriterion("ZIP not like", value, "zip");
			return (Criteria) this;
		}

		public Criteria andZipIn(List<String> values) {
			addCriterion("ZIP in", values, "zip");
			return (Criteria) this;
		}

		public Criteria andZipNotIn(List<String> values) {
			addCriterion("ZIP not in", values, "zip");
			return (Criteria) this;
		}

		public Criteria andZipBetween(String value1, String value2) {
			addCriterion("ZIP between", value1, value2, "zip");
			return (Criteria) this;
		}

		public Criteria andZipNotBetween(String value1, String value2) {
			addCriterion("ZIP not between", value1, value2, "zip");
			return (Criteria) this;
		}

		public Criteria andCountryIsNull() {
			addCriterion("COUNTRY is null");
			return (Criteria) this;
		}

		public Criteria andCountryIsNotNull() {
			addCriterion("COUNTRY is not null");
			return (Criteria) this;
		}

		public Criteria andCountryEqualTo(String value) {
			addCriterion("COUNTRY =", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotEqualTo(String value) {
			addCriterion("COUNTRY <>", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThan(String value) {
			addCriterion("COUNTRY >", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryGreaterThanOrEqualTo(String value) {
			addCriterion("COUNTRY >=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThan(String value) {
			addCriterion("COUNTRY <", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLessThanOrEqualTo(String value) {
			addCriterion("COUNTRY <=", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryLike(String value) {
			addCriterion("COUNTRY like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotLike(String value) {
			addCriterion("COUNTRY not like", value, "country");
			return (Criteria) this;
		}

		public Criteria andCountryIn(List<String> values) {
			addCriterion("COUNTRY in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotIn(List<String> values) {
			addCriterion("COUNTRY not in", values, "country");
			return (Criteria) this;
		}

		public Criteria andCountryBetween(String value1, String value2) {
			addCriterion("COUNTRY between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andCountryNotBetween(String value1, String value2) {
			addCriterion("COUNTRY not between", value1, value2, "country");
			return (Criteria) this;
		}

		public Criteria andPersonIdIsNull() {
			addCriterion("PERSON_ID is null");
			return (Criteria) this;
		}

		public Criteria andPersonIdIsNotNull() {
			addCriterion("PERSON_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPersonIdEqualTo(Long value) {
			addCriterion("PERSON_ID =", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdNotEqualTo(Long value) {
			addCriterion("PERSON_ID <>", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdGreaterThan(Long value) {
			addCriterion("PERSON_ID >", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdGreaterThanOrEqualTo(Long value) {
			addCriterion("PERSON_ID >=", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdLessThan(Long value) {
			addCriterion("PERSON_ID <", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdLessThanOrEqualTo(Long value) {
			addCriterion("PERSON_ID <=", value, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdIn(List<Long> values) {
			addCriterion("PERSON_ID in", values, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdNotIn(List<Long> values) {
			addCriterion("PERSON_ID not in", values, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdBetween(Long value1, Long value2) {
			addCriterion("PERSON_ID between", value1, value2, "personId");
			return (Criteria) this;
		}

		public Criteria andPersonIdNotBetween(Long value1, Long value2) {
			addCriterion("PERSON_ID not between", value1, value2, "personId");
			return (Criteria) this;
		}

		public Criteria andProxyLikeInsensitive(String value) {
			addCriterion("upper(PROXY) like", value.toUpperCase(), "proxy");
			return (Criteria) this;
		}

		public Criteria andIsPrimaryLikeInsensitive(String value) {
			addCriterion("upper(IS_PRIMARY) like", value.toUpperCase(), "isPrimary");
			return (Criteria) this;
		}

		public Criteria andAddressTypeLikeInsensitive(String value) {
			addCriterion("upper(ADDRESS_TYPE) like", value.toUpperCase(), "addressType");
			return (Criteria) this;
		}

		public Criteria andLine1LikeInsensitive(String value) {
			addCriterion("upper(LINE1) like", value.toUpperCase(), "line1");
			return (Criteria) this;
		}

		public Criteria andLine2LikeInsensitive(String value) {
			addCriterion("upper(LINE2) like", value.toUpperCase(), "line2");
			return (Criteria) this;
		}

		public Criteria andLine3LikeInsensitive(String value) {
			addCriterion("upper(LINE3) like", value.toUpperCase(), "line3");
			return (Criteria) this;
		}

		public Criteria andLine4LikeInsensitive(String value) {
			addCriterion("upper(LINE4) like", value.toUpperCase(), "line4");
			return (Criteria) this;
		}

		public Criteria andLine5LikeInsensitive(String value) {
			addCriterion("upper(LINE5) like", value.toUpperCase(), "line5");
			return (Criteria) this;
		}

		public Criteria andCityLikeInsensitive(String value) {
			addCriterion("upper(CITY) like", value.toUpperCase(), "city");
			return (Criteria) this;
		}

		public Criteria andStateLikeInsensitive(String value) {
			addCriterion("upper(STATE) like", value.toUpperCase(), "state");
			return (Criteria) this;
		}

		public Criteria andZipLikeInsensitive(String value) {
			addCriterion("upper(ZIP) like", value.toUpperCase(), "zip");
			return (Criteria) this;
		}

		public Criteria andCountryLikeInsensitive(String value) {
			addCriterion("upper(COUNTRY) like", value.toUpperCase(), "country");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ADDRESS
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 06 19:44:43 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}