package me.bs.java.usermanagement.backend.model;

import java.io.Serializable;

public class Address implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String proxy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String isPrimary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.ADDRESS_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String addressType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.LINE1
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String line1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.LINE2
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String line2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.LINE3
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String line3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.LINE4
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String line4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.LINE5
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String line5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.CITY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.STATE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.ZIP
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String zip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.COUNTRY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ADDRESS.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private Long personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.ID
	 * @return  the value of ADDRESS.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.ID
	 * @param id  the value for ADDRESS.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.PROXY
	 * @return  the value of ADDRESS.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getProxy() {
		return proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.PROXY
	 * @param proxy  the value for ADDRESS.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setProxy(String proxy) {
		this.proxy = proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.IS_PRIMARY
	 * @return  the value of ADDRESS.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getIsPrimary() {
		return isPrimary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.IS_PRIMARY
	 * @param isPrimary  the value for ADDRESS.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setIsPrimary(String isPrimary) {
		this.isPrimary = isPrimary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.ADDRESS_TYPE
	 * @return  the value of ADDRESS.ADDRESS_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getAddressType() {
		return addressType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.ADDRESS_TYPE
	 * @param addressType  the value for ADDRESS.ADDRESS_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.LINE1
	 * @return  the value of ADDRESS.LINE1
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLine1() {
		return line1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.LINE1
	 * @param line1  the value for ADDRESS.LINE1
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLine1(String line1) {
		this.line1 = line1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.LINE2
	 * @return  the value of ADDRESS.LINE2
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLine2() {
		return line2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.LINE2
	 * @param line2  the value for ADDRESS.LINE2
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLine2(String line2) {
		this.line2 = line2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.LINE3
	 * @return  the value of ADDRESS.LINE3
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLine3() {
		return line3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.LINE3
	 * @param line3  the value for ADDRESS.LINE3
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLine3(String line3) {
		this.line3 = line3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.LINE4
	 * @return  the value of ADDRESS.LINE4
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLine4() {
		return line4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.LINE4
	 * @param line4  the value for ADDRESS.LINE4
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLine4(String line4) {
		this.line4 = line4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.LINE5
	 * @return  the value of ADDRESS.LINE5
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLine5() {
		return line5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.LINE5
	 * @param line5  the value for ADDRESS.LINE5
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLine5(String line5) {
		this.line5 = line5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.CITY
	 * @return  the value of ADDRESS.CITY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.CITY
	 * @param city  the value for ADDRESS.CITY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.STATE
	 * @return  the value of ADDRESS.STATE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.STATE
	 * @param state  the value for ADDRESS.STATE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.ZIP
	 * @return  the value of ADDRESS.ZIP
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.ZIP
	 * @param zip  the value for ADDRESS.ZIP
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.COUNTRY
	 * @return  the value of ADDRESS.COUNTRY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.COUNTRY
	 * @param country  the value for ADDRESS.COUNTRY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ADDRESS.PERSON_ID
	 * @return  the value of ADDRESS.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Long getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ADDRESS.PERSON_ID
	 * @param personId  the value for ADDRESS.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ADDRESS
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", proxy=").append(proxy);
		sb.append(", isPrimary=").append(isPrimary);
		sb.append(", addressType=").append(addressType);
		sb.append(", line1=").append(line1);
		sb.append(", line2=").append(line2);
		sb.append(", line3=").append(line3);
		sb.append(", line4=").append(line4);
		sb.append(", line5=").append(line5);
		sb.append(", city=").append(city);
		sb.append(", state=").append(state);
		sb.append(", zip=").append(zip);
		sb.append(", country=").append(country);
		sb.append(", personId=").append(personId);
		sb.append("]");
		return sb.toString();
	}
}