package me.bs.java.usermanagement.backend.model;

import java.util.ArrayList;
import java.util.List;

public class PersonCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public PersonCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProxyIsNull() {
			addCriterion("PROXY is null");
			return (Criteria) this;
		}

		public Criteria andProxyIsNotNull() {
			addCriterion("PROXY is not null");
			return (Criteria) this;
		}

		public Criteria andProxyEqualTo(String value) {
			addCriterion("PROXY =", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotEqualTo(String value) {
			addCriterion("PROXY <>", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyGreaterThan(String value) {
			addCriterion("PROXY >", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyGreaterThanOrEqualTo(String value) {
			addCriterion("PROXY >=", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLessThan(String value) {
			addCriterion("PROXY <", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLessThanOrEqualTo(String value) {
			addCriterion("PROXY <=", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyLike(String value) {
			addCriterion("PROXY like", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotLike(String value) {
			addCriterion("PROXY not like", value, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyIn(List<String> values) {
			addCriterion("PROXY in", values, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotIn(List<String> values) {
			addCriterion("PROXY not in", values, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyBetween(String value1, String value2) {
			addCriterion("PROXY between", value1, value2, "proxy");
			return (Criteria) this;
		}

		public Criteria andProxyNotBetween(String value1, String value2) {
			addCriterion("PROXY not between", value1, value2, "proxy");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("TITLE is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("TITLE =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("TITLE <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("TITLE >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("TITLE >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("TITLE <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("TITLE <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("TITLE like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("TITLE not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("TITLE in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("TITLE not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("TITLE between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("TITLE not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNull() {
			addCriterion("FIRST_NAME is null");
			return (Criteria) this;
		}

		public Criteria andFirstNameIsNotNull() {
			addCriterion("FIRST_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andFirstNameEqualTo(String value) {
			addCriterion("FIRST_NAME =", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotEqualTo(String value) {
			addCriterion("FIRST_NAME <>", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThan(String value) {
			addCriterion("FIRST_NAME >", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameGreaterThanOrEqualTo(String value) {
			addCriterion("FIRST_NAME >=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThan(String value) {
			addCriterion("FIRST_NAME <", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLessThanOrEqualTo(String value) {
			addCriterion("FIRST_NAME <=", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameLike(String value) {
			addCriterion("FIRST_NAME like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotLike(String value) {
			addCriterion("FIRST_NAME not like", value, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameIn(List<String> values) {
			addCriterion("FIRST_NAME in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotIn(List<String> values) {
			addCriterion("FIRST_NAME not in", values, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameBetween(String value1, String value2) {
			addCriterion("FIRST_NAME between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andFirstNameNotBetween(String value1, String value2) {
			addCriterion("FIRST_NAME not between", value1, value2, "firstName");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNull() {
			addCriterion("LAST_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLastNameIsNotNull() {
			addCriterion("LAST_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLastNameEqualTo(String value) {
			addCriterion("LAST_NAME =", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotEqualTo(String value) {
			addCriterion("LAST_NAME <>", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThan(String value) {
			addCriterion("LAST_NAME >", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameGreaterThanOrEqualTo(String value) {
			addCriterion("LAST_NAME >=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThan(String value) {
			addCriterion("LAST_NAME <", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLessThanOrEqualTo(String value) {
			addCriterion("LAST_NAME <=", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameLike(String value) {
			addCriterion("LAST_NAME like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotLike(String value) {
			addCriterion("LAST_NAME not like", value, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameIn(List<String> values) {
			addCriterion("LAST_NAME in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotIn(List<String> values) {
			addCriterion("LAST_NAME not in", values, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameBetween(String value1, String value2) {
			addCriterion("LAST_NAME between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andLastNameNotBetween(String value1, String value2) {
			addCriterion("LAST_NAME not between", value1, value2, "lastName");
			return (Criteria) this;
		}

		public Criteria andFullNameIsNull() {
			addCriterion("FULL_NAME is null");
			return (Criteria) this;
		}

		public Criteria andFullNameIsNotNull() {
			addCriterion("FULL_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andFullNameEqualTo(String value) {
			addCriterion("FULL_NAME =", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameNotEqualTo(String value) {
			addCriterion("FULL_NAME <>", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameGreaterThan(String value) {
			addCriterion("FULL_NAME >", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameGreaterThanOrEqualTo(String value) {
			addCriterion("FULL_NAME >=", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameLessThan(String value) {
			addCriterion("FULL_NAME <", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameLessThanOrEqualTo(String value) {
			addCriterion("FULL_NAME <=", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameLike(String value) {
			addCriterion("FULL_NAME like", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameNotLike(String value) {
			addCriterion("FULL_NAME not like", value, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameIn(List<String> values) {
			addCriterion("FULL_NAME in", values, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameNotIn(List<String> values) {
			addCriterion("FULL_NAME not in", values, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameBetween(String value1, String value2) {
			addCriterion("FULL_NAME between", value1, value2, "fullName");
			return (Criteria) this;
		}

		public Criteria andFullNameNotBetween(String value1, String value2) {
			addCriterion("FULL_NAME not between", value1, value2, "fullName");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("EMAIL is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("EMAIL is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("EMAIL =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("EMAIL <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("EMAIL >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("EMAIL >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("EMAIL <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("EMAIL <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("EMAIL like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("EMAIL not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("EMAIL in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("EMAIL not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("EMAIL between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("EMAIL not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andProxyLikeInsensitive(String value) {
			addCriterion("upper(PROXY) like", value.toUpperCase(), "proxy");
			return (Criteria) this;
		}

		public Criteria andTitleLikeInsensitive(String value) {
			addCriterion("upper(TITLE) like", value.toUpperCase(), "title");
			return (Criteria) this;
		}

		public Criteria andFirstNameLikeInsensitive(String value) {
			addCriterion("upper(FIRST_NAME) like", value.toUpperCase(), "firstName");
			return (Criteria) this;
		}

		public Criteria andLastNameLikeInsensitive(String value) {
			addCriterion("upper(LAST_NAME) like", value.toUpperCase(), "lastName");
			return (Criteria) this;
		}

		public Criteria andFullNameLikeInsensitive(String value) {
			addCriterion("upper(FULL_NAME) like", value.toUpperCase(), "fullName");
			return (Criteria) this;
		}

		public Criteria andEmailLikeInsensitive(String value) {
			addCriterion("upper(EMAIL) like", value.toUpperCase(), "email");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PERSON
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 06 19:44:43 IST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}