package me.bs.java.usermanagement.backend.model;

import java.io.Serializable;

public class Person implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String proxy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.TITLE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.FIRST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String firstName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.LAST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String lastName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.FULL_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String fullName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PERSON.EMAIL
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.ID
	 * @return  the value of PERSON.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.ID
	 * @param id  the value for PERSON.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.PROXY
	 * @return  the value of PERSON.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getProxy() {
		return proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.PROXY
	 * @param proxy  the value for PERSON.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setProxy(String proxy) {
		this.proxy = proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.TITLE
	 * @return  the value of PERSON.TITLE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.TITLE
	 * @param title  the value for PERSON.TITLE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.FIRST_NAME
	 * @return  the value of PERSON.FIRST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.FIRST_NAME
	 * @param firstName  the value for PERSON.FIRST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.LAST_NAME
	 * @return  the value of PERSON.LAST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.LAST_NAME
	 * @param lastName  the value for PERSON.LAST_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.FULL_NAME
	 * @return  the value of PERSON.FULL_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getFullName() {
		return fullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.FULL_NAME
	 * @param fullName  the value for PERSON.FULL_NAME
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PERSON.EMAIL
	 * @return  the value of PERSON.EMAIL
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PERSON.EMAIL
	 * @param email  the value for PERSON.EMAIL
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PERSON
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", proxy=").append(proxy);
		sb.append(", title=").append(title);
		sb.append(", firstName=").append(firstName);
		sb.append(", lastName=").append(lastName);
		sb.append(", fullName=").append(fullName);
		sb.append(", email=").append(email);
		sb.append("]");
		return sb.toString();
	}
}