package me.bs.java.usermanagement.backend.model;

import java.io.Serializable;

public class Phone implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.NUMBER
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String number;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String isPrimary;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String proxy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.PHONE_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private String phoneType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PHONE.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private Long personId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PHONE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.ID
	 * @return  the value of PHONE.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.ID
	 * @param id  the value for PHONE.ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.NUMBER
	 * @return  the value of PHONE.NUMBER
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.NUMBER
	 * @param number  the value for PHONE.NUMBER
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setNumber(String number) {
		this.number = number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.IS_PRIMARY
	 * @return  the value of PHONE.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getIsPrimary() {
		return isPrimary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.IS_PRIMARY
	 * @param isPrimary  the value for PHONE.IS_PRIMARY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setIsPrimary(String isPrimary) {
		this.isPrimary = isPrimary;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.PROXY
	 * @return  the value of PHONE.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getProxy() {
		return proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.PROXY
	 * @param proxy  the value for PHONE.PROXY
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setProxy(String proxy) {
		this.proxy = proxy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.PHONE_TYPE
	 * @return  the value of PHONE.PHONE_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public String getPhoneType() {
		return phoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.PHONE_TYPE
	 * @param phoneType  the value for PHONE.PHONE_TYPE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PHONE.PERSON_ID
	 * @return  the value of PHONE.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public Long getPersonId() {
		return personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PHONE.PERSON_ID
	 * @param personId  the value for PHONE.PERSON_ID
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	public void setPersonId(Long personId) {
		this.personId = personId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PHONE
	 * @mbg.generated  Sat Apr 06 20:22:22 IST 2019
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", number=").append(number);
		sb.append(", isPrimary=").append(isPrimary);
		sb.append(", proxy=").append(proxy);
		sb.append(", phoneType=").append(phoneType);
		sb.append(", personId=").append(personId);
		sb.append("]");
		return sb.toString();
	}
}